### ISSUE TITLE
Cannot get `omrdatasettools` to work: Module not found

### ISSUE THREAD

**Issue by piegamesde** [OMR-Research/MeasureDetector#1]
I've installed the module using `pip install --user omrdatasettools`. When I run `python prepare_muscima-pp_dataset.py` in the `StaveDetector` folder, I then get:

```
Traceback (most recent call last):
  File "prepare_muscima-pp_dataset.py", line 4, in <module>
    from omrdatasettools.converters.ImageColorInverter import ImageColorInverter
ModuleNotFoundError: No module named 'omrdatasettools.converters'
```

**Comment by apacha** [comment]
Thanks for reporting this!

The easiest solution is to pick version 0.19 of omrdatasettools (replace >= with == in requirements.txt). However, I will try to update this to work with the newest version of the datasettools.

**Comment by piegamesde** [comment]
Thanks, pinning the version to `0.19` resolves that error.

However, I get a bunch of other `ModuleNotFoundError`s when executing the commands from the documentation:

```
python research/object_detection/legacy/train.py \
  --pipeline_config_path="MeasureDetector/configurations/faster_rcnn_inception_v2_all_datasets.config" \
  --train_dir="data/faster_rcnn_inception_v2_all_datasets"
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "research/object_detection/legacy/train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
ModuleNotFoundError: No module named 'object_detection'
```

I also had a lot of such errors when trying out the `StaveDetector`, but I could resolve them by replacing lines like `from MeasureDetector.errors import InvalidImageFormatError, InvalidImageError` with `from errors import InvalidImageFormatError, InvalidImageError`. Still weird.

**Comment by apacha** [comment]
As for that error, I know how to resolve it and it's described in the [README.md](https://github.com/OMR-Research/MeasureDetector/blob/master/README.md#permanently-linking-the-source-code-as-pip-package-recommended). Let me know if that resolved your error.

**Comment by piegamesde** [comment]
Yes, that worked. Interestingly enough, the "temporary" version somehow doesn't work for me.

**Comment by piegamesde** [comment]
Finally found the error. The command from the README.md adds `$(pwd)/MeasureDetector` to the `PYTHONPATH`, but according to the section above it should be `$(pwd)` instead.
