### ISSUE TITLE
Upgrade tensorflow to 2.0

### ISSUE THREAD

**Issue by piegamesde** [OMR-Research/MeasureDetector#2]
While the `requirements.txt` as the tensorflow library pinned to version `1.13.1`, this is of little use because pip doesn't provide any older versions for download. I also tried downgrading some packages, but this would require downgrading my whole system to Python 3.7, which is not feasible.

**Comment by apacha** [comment]
I'd love to upgrade to TF 2.0, but the underlying object detection framework (by Google) that is being used in this project explicitly states that [they will not upgrade to version 2.0](https://github.com/tensorflow/models/tree/master/research/object_detection). Please open a respective ticket there, upgrade the project, or use a virtual environment (recommended, e.g., with anaconda) with a compatible Python version.
