### ISSUE TITLE
pycocotools link is broken

### ISSUE THREAD

**Issue by piegamesde** [OMR-Research/MeasureDetector#3]
The Readme links to <https://github.com/waleedka/cocoapi>, which doesn't exist anymore.

**Comment by apacha** [comment]
The official source is https://github.com/cocodataset/cocoapi
Please try if you can install if from there. 
For Windows, there seems to be a fork that is working as well: https://pypi.org/project/pycocotools-windows/

In case you want to run the official source on Windows, there seems to be a fix available:
https://github.com/cocodataset/cocoapi/issues/51#issuecomment-379872704
