### ISSUE TITLE
Examples using the Measure Detector Model with TF under Java

### ISSUE THREAD

**Issue by lukas681** [OMR-Research/MeasureDetector#8]
Hi,
Is there any running example or documentation available for the Measure Detector running with TF on java? I am currently trying to include the Measure Detector in one of my applications and I saw some old documentation on one of the commits like 3 years ago, so maybe there are still some examples.

I would assume that something like that should work:

```
       try(Graph graph = new Graph()) {
           graph.importGraphDef(Files.readAllBytes(modelPath) );
           // Opens up the session
           try (Session ses = new Session(graph)) {
               BufferedImage img = null;
               try {
                   img = ImageIO.read(new File("build/res/testTitle/split/test.png"));
                   System.out.println(img);
               } catch (IOException e) {
                   e.printStackTrace();
               }
               long t = System.currentTimeMillis();
              inputTensor = makeImageTensor(img);
                  output = ses.runner()
                      .feed("image_tensor", inputTensor)
                      .fetch("num_detections")
                      .fetch("detection_boxes")
                      .fetch("detection_scores")
                      .fetch("detection_classes")
                      .run();
```
But I always get the same result:

`UINT8 tensor with shape [1, 761, 502, 3]
[FLOAT tensor with shape [1], FLOAT tensor with shape [1, 600, 4], FLOAT tensor with shape [1, 600], FLOAT tensor with shape [1, 600]]`

Help would be appreciated :)

Best Regards,
Lukas

**Comment by apacha** [comment]
I never tried to run model inference in Java, but could it be that what you are getting is actually the result? The first tensor is potentially the input image (batchsize 1 x 761 (width) x 502 (height) x 3 (color channels)), the one-dimensional tensor is the number of detections, ....
I think 600 is the maximum number of objects that are being predicted with the currently trained model. Have a look at the values of those tensors.

**Comment by apacha** [comment]
@lukas681 Have you been able to investigate what those numbers are? If I don't hear anything from you, then I will close this ticket.
