### ISSUE TITLE
Protobuf error message while running the inference script

### ISSUE THREAD

**Issue by weefeen** [OMR-Research/MeasureDetector#9]
Hi
I can run the inference on the demo model without any issue.

However I tried to go to the steps of the training to export a "saved_model"

I went throught all your steps and I could train successfully based the dataset MUSCIMA++
and export the "saved_model".

However, if I try to run the inference script then I get an issue as follow:

Traceback (most recent call last):
  File "standalone_inference_over_image.py", line 70, in <module>
    detection_graph = load_detection_graph(args.detection_inference_graph)
  File "standalone_inference_over_image.py", line 47, in load_detection_graph
    od_graph_def.ParseFromString(serialized_graph)
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'

I tried several time and trying with different config files that you provide but I get the same issue in all the cases.

Do you have any idea on how to solve this issue?

Thank you very much

**Comment by apacha** [comment]
I haven't trained the model in quite a while. The error sounds like the underlying Tensorflow Library has changed and the exported model can't be read anymore. Can you try to check if you are using the exact same tensorflow version for training that you are using for inference. Maybe I forgot to pin the libraries - I had tons of issues related to underlying libraries being upgraded and becoming incompatible, especially with Tensorflow. The library and API changes so rapidly that I decided to switch to PyTorch.

**Comment by weefeen** [comment]
Thanks

I am using for both the training and the inference the Tensorflow 1.13.1 as instructed.
As you think this is maybe due to version issue, I will review one by one the dependencies version of my anaconda virtual environment. If you have any other idea, please let me know. Thxs

**Comment by weefeen** [comment]
Can it be linked to the version of Protobuf? I followed your instruction on installation of Protobuf. With your command line, the Protobuf - 3.19.1 has been installed.
in your requirements.txt it looks like there is no strong constraint on the version. There seems to have a comment to have version 3.4.0 in case of windows. But in the case of Linux, there seems to have no specific requirement of version.
If I try to install older package, then it will simply show the following message: tensorflow 1.13.1 requires protobuf >= 3.6.1

**Comment by apacha** [comment]
Yes, it could be linked to the used version of protobuf. I remember that there was some issue with newer versions. That's why I manually used another version, see https://github.com/OMR-Research/MeasureDetector/blob/master/MeasureDetector/DownloadAndBuildProtocolBuffers.ps1
The bug was apparently fixed in protobuf 3.10 (see https://github.com/protocolbuffers/protobuf/issues/3957), so you might try a more recent version.

But after having a second look, if you were able to build the protobuf files (in any newer version), then this is probably not the cause for this problem.

**Comment by weefeen** [comment]
Hi Alexander

Actually I found the mistake I did.
I tried to do the inference based on the saved_model.pb. This does not work
However there is also the frozen_inference_graph.pb which is generated. And with this file it works!
 
 Thanks for your support and great work!
 
 Julien

**Comment by apacha** [comment]
I'm happy to hear that it works now!
